"""volumito - Python client library and CLI tool for Volumio.

:copyright: Copyright (C) 2025-2026 Alberto Pettarin
:license: GNU General Public License v3.0 (see the LICENSE file for details)
"""

from volumito.clients import (
    VOLUMIO_INTERNAL_ROOT,
    VOLUMIO_MNT_ROOT,
    Album,
    Artist,
    CollectionStatistics,
    CommandResponse,
    DeviceState,
    Label,
    Notification,
    NotificationListener,
    Notifications,
    Place,
    PlayerState,
    Playlist,
    Playlists,
    PushNotification,
    Queue,
    QueueTrack,
    RemoteCommandResult,
    SearchResultItem,
    SearchResultItemKind,
    SearchResultList,
    SearchResults,
    Story,
    SuccessResponse,
    SystemInfo,
    SystemVersion,
    VolumioAPIError,
    VolumioConnectionError,
    VolumioError,
    VolumioHostConfiguration,
    VolumioModel,
    VolumioMPDClient,
    VolumioRESTAPIClient,
    VolumioSCPError,
    VolumioSSHError,
    VolumioStoryError,
    Zone,
    Zones,
    copy_from_host,
    copy_to_host,
    execute_on_host,
    is_local_file_uri,
    receiver_url,
    remote_music_path,
)

__version__ = "0.0.38"
__author__ = "Alberto Pettarin"
__email__ = "alberto@albertopettarin.it"

__all__ = [
    "Album",
    "Artist",
    "Label",
    "Place",
    "CollectionStatistics",
    "CommandResponse",
    "DeviceState",
    "Notification",
    "Notifications",
    "PlayerState",
    "Playlist",
    "Playlists",
    "PushNotification",
    "Queue",
    "QueueTrack",
    "SearchResultItem",
    "SearchResultItemKind",
    "SearchResultList",
    "SearchResults",
    "Story",
    "SuccessResponse",
    "SystemInfo",
    "SystemVersion",
    "VolumioModel",
    "Zone",
    "Zones",
    "NotificationListener",
    "receiver_url",
    "VOLUMIO_INTERNAL_ROOT",
    "VOLUMIO_MNT_ROOT",
    "RemoteCommandResult",
    "copy_from_host",
    "copy_to_host",
    "execute_on_host",
    "is_local_file_uri",
    "remote_music_path",
    "VolumioHostConfiguration",
    "VolumioRESTAPIClient",
    "VolumioMPDClient",
    "VolumioError",
    "VolumioConnectionError",
    "VolumioAPIError",
    "VolumioSCPError",
    "VolumioSSHError",
    "VolumioStoryError",
]
